### PR TITLE
fix(edge): UnixDomainSocketEndPoint is available in .NET 2.1 and greater

### LINKED ISSUE #1804: [Bug Report] ModuleClient.CreateFromEnvironmentAsync throws an error running inside a .Net 5 ASP.NET Core app
# Context

- **OS, version, SKU and CPU architecture used:** Windows 10 1809 Desktop x64 
- **Application's .NET Target Framework :** net5.0 
- **Device:** Azure Win10 1809 VM 
- **SDK version used:** Microsoft.Azure.Devices.Client" Version 1.35.0

## Description of the issue
Running a ASP.NET Core app inside Azure IoT Edge:
ModuleClient.CreateFromEnvironmentAsync throws an error running inside a .Net 5 ASP.NET Core app

## Code sample exhibiting the issue
```
   public class Program
   {
      public static async Task Main(string[] args)
      {
         var host = CreateHostBuilder(args).Build();
         var transportSetting = new MqttTransportSettings(TransportType.Mqtt_Tcp_Only);

         ITransportSettings[] ts = { transportSetting };
         var client = await ModuleClient.CreateFromEnvironmentAsync();

         var twin = client.GetTwinAsync().GetAwaiter().GetResult();

         Console.WriteLine($"Twin.Properties.Desired.ToJson : {twin.Properties.Desired.ToJson()}");

         await host.RunAsync();
      }

      public static IHostBuilder CreateHostBuilder(string[] args) =>
          Host.CreateDefaultBuilder(args)
              .ConfigureWebHostDefaults(webBuilder =>
              {
                 webBuilder.UseStartup<Startup>();
              });
   }

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <UserSecretsId>ed801301-1e44-4b8f-b1af-149350b5f235</UserSecretsId>
    <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.35.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.0.7" />
  </ItemGroup>

</Project>
```

## Console log of the issue
Unhandled exception. System.Net.Sockets.SocketException (10014): The system detected an invalid pointer address in attempting to use a pointer argument in a call.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
   at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, EndPoint remoteEP)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.Transport.HttpUdsMessageHandler.GetConnectedSocketAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.Transport.HttpUdsMessageHandler.GetConnectedSocketAsync()
   at Microsoft.Azure.Devices.Client.HsmAuthentication.Transport.HttpUdsMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.Transport.HttpUdsMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.GeneratedCode.HttpHsmClient.TrustBundleAsync(String api_version, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.GeneratedCode.HttpHsmClient.TrustBundleAsync(String api_version, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.GeneratedCode.HttpHsmClient.TrustBundleAsync(String api_version)
   at Microsoft.Azure.Devices.Client.Edge.TrustBundleProvider.<>c__DisplayClass3_0.<GetTrustBundleWithRetryAsync>b__0()
   at Microsoft.Azure.Devices.Client.TransientFaultHandling.AsyncExecution`1.ExecuteAsyncImpl(Task ignore)
   at Microsoft.Azure.Devices.Client.TransientFaultHandling.AsyncExecution`1.ExecuteAsync()
   at Microsoft.Azure.Devices.Client.TransientFaultHandling.RetryPolicy.ExecuteAsync[TResult](Func`1 taskFunc, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.TransientFaultHandling.RetryPolicy.ExecuteAsync[TResult](Func`1 taskFunc)
   at Microsoft.Azure.Devices.Client.Edge.TrustBundleProvider.GetTrustBundleWithRetryAsync(HttpHsmClient hsmHttpClient, String apiVersion)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Devices.Client.Edge.TrustBundleProvider.GetTrustBundleWithRetryAsync(HttpHsmClient hsmHttpClient, String apiVersion)
   at Microsoft.Azure.Devices.Client.Edge.TrustBundleProvider.GetTrustBundleAsync(Uri providerUri, String apiVersion)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Devices.Client.Edge.TrustBundleProvider.GetTrustBundleAsync(Uri providerUri, String apiVersion)
   at Microsoft.Azure.Devices.Client.Edge.EdgeModuleClientFactory.CreateInternalClientFromEnvironmentAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Devices.Client.Edge.EdgeModuleClientFactory.CreateInternalClientFromEnvironmentAsync()
   at Microsoft.Azure.Devices.Client.Edge.EdgeModuleClientFactory.CreateAsync()
   at Microsoft.Azure.Devices.Client.ModuleClient.CreateFromEnvironmentAsync(ITransportSettings[] transportSettings, ClientOptions options)
   at Microsoft.Azure.Devices.Client.ModuleClient.CreateFromEnvironmentAsync(TransportType transportType, ClientOptions options)
   at Microsoft.Azure.Devices.Client.ModuleClient.CreateFromEnvironmentAsync(ClientOptions options)
   at WebApplication4.Program.Main(String[] args) in C:\src\WebApplication4\Program.cs:line 24
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at WebApplication4.Program.Main(String[] args)
   at WebApplication4.Program.<Main>(String[] args)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.HsmAuthentication.Transport.HttpUdsMessageHandler.GetConnectedSocketAsync()
   at Microsoft.Azure.Devices.Client.HsmAuthentication.Transport.HttpUdsMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.GeneratedCode.HttpHsmClient.TrustBundleAsync(String api_version, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Edge.TrustBundleProvider.GetTrustBundleWithRetryAsync(HttpHsmClient hsmHttpClient, String apiVersion)
   at Microsoft.Azure.Devices.Client.Edge.TrustBundleProvider.GetTrustBundleAsync(Uri providerUri, String apiVersion)
   at Microsoft.Azure.Devices.Client.Edge.EdgeModuleClientFactory.CreateInternalClientFromEnvironmentAsync()
   at WebApplication4.Program.Main(String[] args) in C:\src\WebApplication4\Program.cs:line 24
   at WebApplication4.Program.<Main>(String[] args)

### PR DESCRIPTION
**Pull request by jamdavi**
Fixes #1804 

The edge client HSM provider uses UnixDomainSockets (UDS) for communication. Before .NET 2.1 to implement a Unix Socket you had to create your own class to do so. Since 2.1 there has been a native UnixDomainSocketEndPoint class in the runtime.

In 2.1 and 3.1 there is no issue. However in 5.0 there are some changes to the way the Socket class handles the native UnixDomainSocketEndPoint class. I didn't dig down extremely deep, but I suspect it's due to the way the endpoint handles the SocketAddress and the string manipulation there seeing as how there is a specific implementation for Windows and for Unix.

## Tested On Windows Containers
dotnetcore 2.1
dotnetcore 3.1
.NET 5.0

### CODE REVIEW

File: iothub/device/src/ModernDotNet/HsmAuthentication/Transport/HttpUdsMessageHandler.cs [hunk 1]
```diff
@@ -42,9 +42,14 @@ protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage
 
         private async Task<Socket> GetConnectedSocketAsync()
         {
-            var endpoint = new UnixDomainSocketEndPoint(_providerUri.LocalPath);
             Socket socket = new Socket(AddressFamily.Unix, SocketType.Stream, ProtocolType.Unspecified);
+#if NET451 || NET472 || NETSTANDARD2_0
+            var endpoint = new UnixDomainSocketEndPoint(_providerUri.LocalPath);
             await socket.ConnectAsync(endpoint).ConfigureAwait(false);
+#else
+            var endpoint = new System.Net.Sockets.UnixDomainSocketEndPoint(_providerUri.LocalPath);
```
Comment (drwill-ms) [inline iothub/device/src/ModernDotNet/HsmAuthentication/Transport/HttpUdsMessageHandler.cs:50]: Isn't `System.Net.Sockets` already in the usings list at the top?

Comment (drwill-ms) [reply iothub/device/src/ModernDotNet/HsmAuthentication/Transport/HttpUdsMessageHandler.cs:50]: What makes this type different than the one on 48?

**Review by drwill-ms — COMMENTED** [review]
I don't understand how this fixes the issue. The only difference in the two code paths seems to be a fully-qualified namespace, which is already in usings. Is there a different type of the same name in a different namespace?

File: iothub/device/src/ModernDotNet/HsmAuthentication/Transport/HttpUdsMessageHandler.cs (hunk 1 above)
Comment (abhipsaMisra) [reply iothub/device/src/ModernDotNet/HsmAuthentication/Transport/HttpUdsMessageHandler.cs:50]: To highlight the difference between using our own impl for <ns2.1 and using System.Net impl for others, we should probably either use a different alias for each UnixDomainSocketEndPoint implementation import or use the full namespace when referencing both of the types.

File: iothub/device/src/ModernDotNet/HsmAuthentication/Transport/HttpUdsMessageHandler.cs [hunk 2]
```diff
@@ -42,9 +42,14 @@ protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage
...
+            await socket.ConnectAsync(endpoint).ConfigureAwait(false);
```
Comment (abhipsaMisra) [inline iothub/device/src/ModernDotNet/HsmAuthentication/Transport/HttpUdsMessageHandler.cs:51]: L48 and L51 call the same API with the same params, it can be moved out of the if-else block.

Comment (abhipsaMisra) [reply iothub/device/src/ModernDotNet/HsmAuthentication/Transport/HttpUdsMessageHandler.cs:51]: I take that back, it is an instance of these types that have different implementations for different frameworks.

**Review by abhipsaMisra — APPROVED** [review]

**Comment by jamdavi** [comment]
> I don't understand how this fixes the issue. The only difference in the two code paths seems to be a fully-qualified namespace, which is already in usings. Is there a different type of the same name in a different namespace?

Correct, the unqualified namespace is an IoT Hub implementation of this class that is needed for CLR versions less than core 2.1.

This change uses the supplied .NET framework implementation for the later versions.

File: iothub/device/src/ModernDotNet/HsmAuthentication/Transport/HttpUdsMessageHandler.cs (hunk 1 above)
Comment (drwill-ms) [reply iothub/device/src/ModernDotNet/HsmAuthentication/Transport/HttpUdsMessageHandler.cs:50]: I'd agree. In the very least, use the fully-qualified namespace for our own impl too, or alias ours.

Comment (drwill-ms) [reply iothub/device/src/ModernDotNet/HsmAuthentication/Transport/HttpUdsMessageHandler.cs:50]: And a code comment more or less what is in this PR description that explains why we have this platform-based code fork.

**Comment by bikamani** [comment]
> > I don't understand how this fixes the issue. The only difference in the two code paths seems to be a fully-qualified namespace, which is already in usings. Is there a different type of the same name in a different namespace?
> 
> Correct, the unqualified class is an IoT Hub implementation of this class that is needed for CLR versions less than core 2.1.
> 
> This change uses the supplied .NET framework implementation for the later versions.

Got it, I got confused with the naming earlier as well. I can see adding a comment/renaming IoT Hub implementation would be useful

File: iothub/device/src/ModernDotNet/HsmAuthentication/Transport/HttpUdsMessageHandler.cs [hunk 3]
```diff
@@ -42,9 +43,27 @@ protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage
...
+             * https://github.com/dotnet/corefx/blob/12b51c6bf153cc237b251a4e264d5e7c0ee84a33/src/System.IO.Pipes/src/System/Net/Sockets/UnixDomainSocketEndPoint.cs
+             * https://github.com/dotnet/corefx/blob/12b51c6bf153cc237b251a4e264d5e7c0ee84a33/src/System.Net.Sockets/tests/FunctionalTests/UnixDomainSocketTest.cs#L248
+             *
+             * Since then the UnixDomainSocketEndpoint has been added to the dotnet framework and there has been considerable work
+             * around unix sockets in the BCL. For older versions of the framework we will continue to use the existing class since it works
+             * fine. For netcore 2.1 and greater as well as .NET 5.0 and greater we'll use the native framework version.
+            */
+#if NET451 || NET472 || NETSTANDARD2_0
+            var endpoint = new UnixDomainSocketEndPoint(_providerUri.LocalPath);
+            await socket.ConnectAsync(endpoint).ConfigureAwait(false);
```
Comment (barustum) [inline iothub/device/src/ModernDotNet/HsmAuthentication/Transport/HttpUdsMessageHandler.cs:62]: maybe the ConnectAsync part can be extracted out of the 'if' and 'else' directives since it's common to both conditions.

**Review by bikamani — APPROVED** [review]

File: iothub/device/src/ModernDotNet/HsmAuthentication/Transport/HttpUdsMessageHandler.cs [hunk 4]
```diff
@@ -42,10 +43,27 @@ protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage
 
         private async Task<Socket> GetConnectedSocketAsync()
         {
-            var endpoint = new UnixDomainSocketEndPoint(_providerUri.LocalPath);
             Socket socket = new Socket(AddressFamily.Unix, SocketType.Stream, ProtocolType.Unspecified);
-            await socket.ConnectAsync(endpoint).ConfigureAwait(false);
 
+            /*
```
Comment (drwill-ms) [inline iothub/device/src/ModernDotNet/HsmAuthentication/Transport/HttpUdsMessageHandler.cs:48]: We exclusively use `//` style comments

File: iothub/device/src/ModernDotNet/HsmAuthentication/Transport/HttpUdsMessageHandler.cs [hunk 5]
```diff
@@ -42,10 +43,27 @@ protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage
...
+             * https://github.com/dotnet/corefx/blob/12b51c6bf153cc237b251a4e264d5e7c0ee84a33/src/System.IO.Pipes/src/System/Net/Sockets/UnixDomainSocketEndPoint.cs
+             * https://github.com/dotnet/corefx/blob/12b51c6bf153cc237b251a4e264d5e7c0ee84a33/src/System.Net.Sockets/tests/FunctionalTests/UnixDomainSocketTest.cs#L248
+             *
+             * Since then the UnixDomainSocketEndpoint has been added to the dotnet framework and there has been considerable work
+             * around unix sockets in the BCL. For older versions of the framework we will continue to use the existing class since it works
+             * fine. For netcore 2.1 and greater as well as .NET 5.0 and greater we'll use the native framework version.
+            */
+
+#if NET451 || NET472 || NETSTANDARD2_0
+            var endpoint = new UnixDomainSocketEndPoint(_providerUri.LocalPath);
```
Comment (drwill-ms) [inline iothub/device/src/ModernDotNet/HsmAuthentication/Transport/HttpUdsMessageHandler.cs:62]: I'd still prefer that you use the fully-qualified namespace here to emphasize these are different types.

**Review by drwill-ms — APPROVED** [review]
