### PR TITLE
fix(iot-device): Fix out-of-date comments on DeviceClient

### LINKED ISSUE #515: Twin.DeviceId and Twin.ModuleId return null
- **OS, version, SKU and CPU architecture used:** <VERSION> Windows 10 Desktop x64
- **Application's .NET Target Framework :** <NETVERSION> netcoreapp2.1
- **Device:** <DEVICETYPE> Surface Pro (i5)
- **SDK version used:** <VERSION> Microsoft.Azure.Devices.Client 1.17.0-preview-007

## Description of the issue:
When calling `Twin.DeviceId` or `Twin.ModuleId`, null is returned.  
other properties (e.g. `Twin.Properties`) are properly populated

## Code sample exhibiting the issue:
```C#
Twin myTwin = await ioTHubModuleClient.GetTwinAsync();
Debug.WriteLine($"Module ID:{myTwin.ModuleId}");
Debug.WriteLine($"Device ID: {myTwin.DeviceId}");
```

## Console log of the issue:
Module ID:
Device ID:

### PR DESCRIPTION
**Pull request by abhipsaMisra**
The only device client creation method where Http and Amqp are the only supported protocols is device client creation using iot-hub scope connection string. (FYI for #1185 )

Also, update comment for GetTwinAsync on Device Client.
Fixes #515

### CODE REVIEW

File: iothub/device/src/ClientFactory.cs [hunk 1]
```diff
@@ -47,7 +47,7 @@ public static InternalClient Create(string hostname, string gatewayHostname, IAu
         /// </summary>
         /// <param name="hostname">The fully-qualified DNS hostname of IoT Hub</param>
         /// <param name="authenticationMethod">The authentication method that is used</param>
-        /// <param name="transportType">The transportType used (Http1 or Amqp)</param>
+        /// <param name="transportType">The transportType used (Http1, Amqp or Mqtt)</param>
```
Comment (prmathur-microsoft) [inline iothub/device/src/ClientFactory.cs:50]: Could we use a url to point to the definition of transport type? I believe there are more right? https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/TransportType.cs

Comment (abhipsaMisra) [reply iothub/device/src/ClientFactory.cs:50]: Amqp and Mqtt cover both the Tcp and WS variants. By defining the transport type as Amqp, the device client will create a prioritized transport list of Amqp_tcp, Amqp_ws (same for Mqtt).

Comment (abhipsaMisra) [reply iothub/device/src/ClientFactory.cs:50]: I can add a link to this file, sure
