### PR TITLE
Retry DeviceClient redesign, ExceptionHandling and CancellationToken support

### LINKED ISSUE #114: Add support for CancellationToken in async methods
I recently started playing with the SDK for a project and noticed that none of the async methods accept a cancellation token. Is a different pattern used in this SDK than cancellation tokens? If not, can we add support for them?

### LINKED ISSUE #222: E2E tests improper use of TPL
A lot of code in the E2E tests are using Tasks the wrong way.
We need to remove all instances of .Result and .GetAwaiter().GetResult().

Initialization can be performed by calling the `async Task` init methods during test execution or using `AsyncLazy<T>` to ensure init-once semantics.

Examples: ClassInitialize/ClassCleanup calls to InitializeEnvironment and CloseAsync().

### LINKED ISSUE #591: Provisioning tests should perform provisioning and IoT Hub communications over the same protocol
A service-level issue prevents device registration and usage over MQTT immediately after provisioning.
Currently the tests always use MQTT after registration. I am temporarily switching this to HTTP.

This issue is tracking a test enhancement to use the same protocol for both registration and IoT Hub.

### LINKED ISSUE #693: Timeout exceptions since version 1.17
Starting with v1.17 I have very frequent Timeout exceptions (>20 % calls) calling either : 
DeviceClient.OpenAsync();
or
DeviceClient.SendEventAsync(message);

DeviceClient instance is created using DeviceClient.CreateFromConnectionString(connectionString, deviceId);
Connection string is only specifying HostName, SharedAccessKeyName and SharedAccessKey.
I have tried using DeviceClient.OperationTimeoutInMilliseconds set to 30 sec. and 60 sec. 
I have less than 10 IoT devices declared.
I have not discovered any way to reproduce the exception systematically.

Using V1.18.1 release, my unit tests using above methods most often fails.
I need to fallback to V1.7.2 to reach again a 100% success. I never had this kind of issue with that version or the previous ones.

Thanks for fixing.

### LINKED ISSUE #702: DeviceClient - Connection recovery
- **OS, version, SKU and CPU architecture used: Windows 10 Desktop x64,** <VERSION> 
- **Application's .NET Target Framework : net461** <NETVERSION> 
- **Device: Laptop** <DEVICETYPE> 
- **SDK version used: 1.17.1** <VERSION> 

## Description of the issue:

When connection state changes to Disabled due to Client_Close reason is it responsibility of application 
to reconnect to IoTHub or DeviceClient should do it? It usually happens when device is changing WiFi access points (if switching takes longer than approximately 2 minutes).

## Console log of the issue:

11:00:01,991;Internal client connection status changed to: Disconnected_Retrying. Status change reason: No_Network.
11:00:03,252;Internal client connection status changed to: Disabled. Status change reason: Client_Close.

### LINKED ISSUE #737: Retries or implicit connects should never happen within the handler
- **OS, version, SKU and CPU architecture used:** Any
- **Application's .NET Target Framework :**All
- **Device:** N/A
- **SDK version used:** master@2018-12-17

## Description of the issue:
As per comment from @CIPop:

"Retries or implicit connects should never happen within the handler. If the transport is closed then you should error out (not a valid state)."

## Code sample exhibiting the issue:
https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/Transport/Mqtt/MqttTransportHandler.cs#L645

And any other occurrences within the Enable*Async methods.

## Console log of the issue:
None. N/A

### PR DESCRIPTION
**Pull request by CIPop**
## Checklist
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/.github/CONTRIBUTING.md).
- [X] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [X] This pull-request is submitted against the `master` branch.

## Description of the changes

This PR addresses part of the reported retry issues caused by state management issues within the transport pipeline.
During our investigations we've found that the AMQP transport will need additional changes (work in progress by @zolvarga).

### Removing incorrect timeout handling

`DeviceClient`/`ModuleClient` Timeout is now achieved only via CancellationToken, using cooperative cancellation. This means that, in certain cases OperationTimeoutMilliseconds may not be honored precisely, as I/O cannot always be cancelled immediately.
If immediate cancellation is needed, DeviceClient should be `Dispose()`d.

### Redesign of the transport pipeline

The pipeline has been modified to include a RetryHandler, ErrorHandler and ProtocolRoutingHandler.
- RetryHandler will perform implicit open and hold the high level state of the client. It is responsible to recreate the state in case the transport layer reports any errors. No other component should attempt operation retry.
- ErrorHandler performs error adaptation for non-AzureIoT specific errors thrown by the transport layer throws (e.g. SocketException or AuthenticationException).
- ProtocolRoutingHandler is iterating through the specified transport types (HTTP/MQTT/AMQP). Once the protocol is selected and the client successfully connected, it will not change it for the life-time of the client. ProtocolRountingHandler is also responsible with transport `Dispose()` in case of fatal errors.

GateKeeperHandler which was responsible with implicit open was removed / merged into RetryHandler.

The pipeline ends with one of the transport handlers: MQTT, AMQP, HTTP

### Exception handling

Exceptions have been unified under the `IotHubException` root type.

|Fault / Type | Retriable | Not retriable |
|---|---|---|
|Server (catch `IotHubException`) | `ServerErrorException`, `QuotaExceededException`, `ServiceBusyException`, `IotHubThrottledException` | `DeviceMessageLockLostException`, `IotHubSuspendedException`, `MessageTooLargeException`, `DeviceMaximumQueueDepthExceededException`, `DeviceAlreadyExistsException`, `UnauthorizedException`, `DeviceNotFoundException` |
|Network | `IotHubCommunicationException` | `System.Security.Authentication.AuthenticationException` | 

For all above exceptions, the `InnerException` will contain more information.

### ConnectionStatusCallback

| Callback status | Reason |
| --- | ---|
| `(ConnectionStatus.Connected, ConnectionStatusChangeReason.Connection_Ok)` | Client connected (initially and after a successful retry). |
| `(ConnectionStatus.Disabled, ConnectionStatusChangeReason.Client_Close)` | Application disposed the client. |
| `(ConnectionStatus.Disconnected, ConnectionStatusChangeReason.Communication_Error)` | If no callback subscriptions exist, the client will not automatically connect. A future operation will attempt to reconnect the client. |
| `(ConnectionStatus.Disconnected_Retrying, ConnectionStatusChangeReason.Communication_Error)` | If any callback subscriptions exist (methods, twin, events) and connectivity is lost, the client will try to reconnect. |
| `(ConnectionStatus.Disconnected, ConnectionStatusChangeReason.Retry_Expired)` | Retry timeout. The RetryHandler will attempt to recover links for a duration of `OperationTimeoutInMilliseconds` (default 4 minutes) according to [this retry policy](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/devdoc/requirements/retrypolicy.md). |
| `(ConnectionStatus.Disconnected, ConnectionStatusChangeReason.Bad_Credential)` | UnauthorizedException during Retry. |
| `(ConnectionStatus.Disconnected, ConnectionStatusChangeReason.Device_Disabled)` | DeviceDisabledException during Retry. |

### Other changes
- Updating all clients to AMQP to 2.3.7
- Fixing DeviceClient MQTT ID generation race condition.
- Logging and test enhancements.

## Reference/Link to the issue solved with this PR (if any)

Ref: #571 #558 #682 #700 #687 #574 #513 #263
Fixes #114
Fixes #591
Fixes #737
Fixes #702
Fixes #693
Fixes #222

### CODE REVIEW

File: iothub/device/src/Transport/ProtocolRoutingDelegatingHandler.cs [hunk 1]
```diff
@@ -1,133 +1,109 @@
...
                 }
 
                 try
                 {
-                    this.Context.Set(transportSetting);
-                    this.InnerHandler = this.ContinuationFactory(this.Context);
-
-                    // Try to open a connection with this transport
-                    await base.OpenAsync(explicitOpen, cancellationToken).ConfigureAwait(false);
+                    await base.OpenAsync(cancellationToken).ConfigureAwait(false);
```
Comment (CIPop) [inline iothub/device/src/Transport/ProtocolRoutingDelegatingHandler.cs]: @prmathur-microsoft this handler should be removed and we should only retry when the error is `IotHubCommunicationException`.

**Comment by CIPop** [comment]
I found at least one of the issues with running in parallel on Linux. It appears that the TPM simulator hangs indefinitely during `TcpTpmDevice.Connect()` against the Docker container:

image

The root cause is that the previous test using TPM didn't release the resource:
image

Another issue is not setting the SocketTimeout to eliminate possible deadlocks.

**Comment by CIPop** [comment]
@zolvarga @prmathur-microsoft  I am seeing failures within the AMQP protocol not being able to create a sending link within 1 minute:

I will merge this as-is for now to get more data from the nightly and scheduled runs and to unblock other check-ins.
I have contacted @amarochk regarding the TPM Connect timeout limitation. If there is no workaround, I will open a https://github.com/Microsoft/TSS.MSR issue.

```
Test method Microsoft.Azure.Devices.E2ETests.ProvisioningE2ETests.ProvisioningDeviceClient_ValidRegistrationId_AmqpWsWithNullProxy_X509Individual_RegisterOk threw exception: 
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: The operation did not complete within the allocated time 00:01:00 for object message. ---> System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object message.
Stack trace
    at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.SendingAmqpLink.EndSendMessage(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.SendAmqpMessageAsync(AmqpMessage amqpMessage, CancellationToken cancellationToken) in /home/vsts/work/1/s/iothub/device/src/Transport/AmqpTransportHandler.cs:line 580
--- End of inner exception stack trace ---
    at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.SendAmqpMessageAsync(AmqpMessage amqpMessage, CancellationToken cancellationToken) in /home/vsts/work/1/s/iothub/device/src/Transport/AmqpTransportHandler.cs:line 584
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.SendEventAsync(Message message, CancellationToken cancellationToken) in /home/vsts/work/1/s/iothub/device/src/Transport/AmqpTransportHandler.cs:line 184
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/iothub/device/src/Transport/ErrorDelegatingHandler.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation) in /home/vsts/work/1/s/iothub/device/src/Transport/ErrorDelegatingHandler.cs:line 163
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass17_0.<<SendEventAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/iothub/device/src/Transport/RetryDelegatingHandler.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken) in /home/vsts/work/1/s/iothub/device/src/Transport/RetryDelegatingHandler.cs:line 78
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message) in /home/vsts/work/1/s/iothub/device/src/InternalClient.cs:line 617
   at Microsoft.Azure.Devices.E2ETests.ProvisioningE2ETests.ProvisioningDeviceClient_ValidRegistrationId_Register_Ok(String transportType, String securityType, Nullable`1 x509EnrollmentType, Nullable`1 transportFallback, Boolean setCustomProxy, String proxyServerAddress) in /home/vsts/work/1/s/e2e/test/netstandard20/ProvisioningE2ETests.cs:line 216
   at Microsoft.Azure.Devices.E2ETests.ProvisioningE2ETests.ProvisioningDeviceClient_ValidRegistrationId_AmqpWsWithNullProxy_X509Individual_RegisterOk() in /home/vsts/work/1/s/e2e/test/netstandard20/ProvisioningE2ETests.cs:line 153
```

**Comment by CIPop** [comment]
Opened https://github.com/Microsoft/TSS.MSR/issues/29 to track the TCP TPM driver limitation.
