### PR TITLE
Fix error mapping for error code iot-hub-not-found-error

### LINKED ISSUE #1312: Not reconnecting after IoT Hub failover when AmqpConnectionPoolSettings.Pooling is enabled
## Description of the issue:
When using the DeviceClient with `AmqpConnectionPoolSettings.Pooling` enabled, the DeviceClient does not reconnect after a [manual initiated failover of the IoT Hub](https://docs.microsoft.com/en-us/azure/iot-hub/tutorial-manual-failover#perform-a-manual-failover).  

With `AmqpConnectionPoolSettings.Pooling` disabled (= false) or other `TransportType` settings such as `Mqtt`  the DeviceClient reconnects after failover and successfully continues sending messages.

## Code sample exhibiting the issue:

The nuget package "Microsoft.Azure.Devices.Client" Version="1.23.2" was used to verify the behavior.

Initialization of the DeviceClient with `AmqpConnectionPoolSettings.Pooling` enabled (= true) leads to the error:
```csharp
_deviceClient = DeviceClient.CreateFromConnectionString(
    _connectionString,
    new ITransportSettings[]
    {
        new AmqpTransportSettings(TransportType.Amqp_Tcp_Only)
        {
            AmqpConnectionPoolSettings = new AmqpConnectionPoolSettings()
            {
                Pooling = true,
            }
        }
    });
```
Initialization of the DeviceClient with `AmqpConnectionPoolSettings.Pooling` disabled (=false), properly reconnects after the failover finished:
```csharp
_deviceClient = DeviceClient.CreateFromConnectionString(
    _connectionString,
    new ITransportSettings[]
    {
        new AmqpTransportSettings(TransportType.Amqp_Tcp_Only)
        {
            AmqpConnectionPoolSettings = new AmqpConnectionPoolSettings()
            {
                Pooling = false,
            }
        }
    });
```

## Console log of the issue:

Calling `await _deviceClient.SendEventAsync(message);` throws during and then after the failover forever on each call an `IotHubException` with an inner exception of type `AmqpException` with message `An AMQP error occurred (condition='com.microsoft:iot-hub-not-found-error')`: 
```
03/04/2020 12:10:35: IotHubException: error(condition:com.microsoft:iot-hub-not-found-error,info:[com.microsoft:tracking-id:9ca84927533546abb68ad3da7b6a0cf4-G:20-TimeStamp:04/03/2020 10:10:34,com.microsoft:is-filtered:True])
        03/04/2020 12:10:35: AmqpException: An AMQP error occurred (condition='com.microsoft:iot-hub-not-found-error').
```

AB#7253018

### PR DESCRIPTION
**Pull request by abhipsaMisra**
AMQP - iot-hub-not-found error will now close the connection and reconnect.
The current behavior was to reconnect at session level itself, but for failover/failback scenarios we require the DNS resolution to happen again.

Fixes #1312

### CODE REVIEW

File: iothub/device/src/Transport/AmqpIoT/AmqpIoTErrorAdapter.cs [hunk 1]
```diff
@@ -38,121 +38,6 @@ internal static class AmqpIoTErrorAdapter
 
         private const int MaxSizeInInfoMap = 32 * 1024;
 
-        public static AmqpException ToAmqpException(Exception exception, string gatewayId)
```
Comment (abhipsaMisra) [inline iothub/device/src/Transport/AmqpIoT/AmqpIoTErrorAdapter.cs:41]: These are legacy-methods were not being referenced by anyone anymore.
